services:
  reminder_app:
    container_name: trello_remidner
    build: .
    env_file:
      - .env
    restart: always
    volumes:
      - .:/TrelloReminder
    # depends_on:
    #   db:
    #    condition: service_healthy

#   db:
#     container_name: db
#     image: postgres:16
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_DB=postgres
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postresql/data
#     healthcheck:
#       test: [ "CMD-SHELL", "sh", "-c", "pg_isready" ]
#       interval: 5s
#       timeout: 60s
#       retries: 5
#       start_period: 80s

# volumes:
#     postgres_data: {}