services:
  reminder_app:
    container_name: trello_remidner
    build:
      context: .
      target: dev
    env_file:
      - .env
    restart: always
    volumes:
      - .:/TrelloReminder
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}